[INFO] Module GCC/9.4.0 loaded.

Inactive Modules:
  1) UCX/1.17.0     2) numactl/2.0.16

The following have been reloaded with a version change:
  1) GCCcore/.11.3.0 => GCCcore/.9.4.0     3) zlib/1.2.13 => zlib/1.2.11
  2) binutils/2.38 => binutils/2.36.1

[INFO] Module CUDA/11.8.0 loaded.
[INFO] Module cuDNN/8.6.0.163-CUDA-11.8.0 loaded.
Traceback (most recent call last):
  File "/home/md334167/elzerman-with-unet/aenc_train.py", line 156, in <module>
    main()
  File "/home/md334167/elzerman-with-unet/aenc_train.py", line 37, in main
    data = np.array([file[key] for key in all_keys])  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 1057, in __array__
    arr = numpy.zeros(self.shape, dtype=self.dtype if dtype is None else dtype)
                                        ^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 540, in dtype
    return self.id.dtype
           ^^^^^^^^^^^^^
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.dtype.__get__
  File "h5py/h5d.pyx", line 184, in h5py.h5d.DatasetID.dtype.__get__
  File "h5py/h5t.pyx", line 439, in h5py.h5t.TypeID.dtype.__get__
  File "h5py/h5t.pyx", line 440, in h5py.h5t.TypeID.dtype.__get__
  File "h5py/h5t.pyx", line 1081, in h5py.h5t.TypeFloatID.py_dtype
ValueError: Insufficient precision in available types to represent (63, 52, 11, 0, 52)
