[INFO] Module GCC/9.4.0 loaded.

Inactive Modules:
  1) UCX/1.17.0     2) numactl/2.0.16

The following have been reloaded with a version change:
  1) GCCcore/.11.3.0 => GCCcore/.9.4.0     3) zlib/1.2.13 => zlib/1.2.11
  2) binutils/2.38 => binutils/2.36.1

[INFO] Module CUDA/11.8.0 loaded.
[INFO] Module cuDNN/8.6.0.163-CUDA-11.8.0 loaded.
Traceback (most recent call last):
  File "/home/md334167/elzerman-with-unet/train_for_exdata.py", line 341, in <module>
    main()
  File "/home/md334167/elzerman-with-unet/train_for_exdata.py", line 238, in main
    train_loader, val_loader, test_loader = get_loaders(amps, amps_dist)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/elzerman-with-unet/train_for_exdata.py", line 125, in get_loaders
    noisy_data = np.array([batch_x.cpu().numpy() for batch_x, batch_y in train_loader])    
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/elzerman-with-unet/train_for_exdata.py", line 125, in <listcomp>
    noisy_data = np.array([batch_x.cpu().numpy() for batch_x, batch_y in train_loader])    
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/rwthfs/rz/cluster/home/md334167/elzerman-with-unet/dataset.py", line 59, in __getitem__
    clean_trace = self.smooth(clean_trace, 20)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SimDataset.smooth() takes 2 positional arguments but 3 were given

